### ISSUE TITLE
No extension incon in system tray

### ISSUE THREAD

**Issue by iadegesso** [cwittenberg/gnome-pushover-messages-unofficial#1]
I installed and configured this extension in my Gentoo based GNOME environment, but in the system tray I can only see an empty region where the extension P icon shoud appear...

Anyway, other features seems to work.

Iade

**Comment by cwittenberg** [comment]
hi @iadegesso  thanks for reporting this. I've added a fix for this. Would be appreciative if you could place some stars here  :) https://extensions.gnome.org/extension/5377/pushover-message-notifications/
